package io.github.kimbongjune.geoserverclient.api.style;

import io.github.kimbongjune.geoserverclient.BaseIntegrationTest;
import io.github.kimbongjune.geoserverclient.dto.style.*;
import io.github.kimbongjune.geoserverclient.dto.workspace.CreateWorkspaceRequest;
import org.junit.jupiter.api.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

import static io.github.kimbongjune.geoserverclient.dto.style.OgcFilters.*;
import static io.github.kimbongjune.geoserverclient.dto.style.SldExpression.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Live integration test: SldBuilder → StyleManager → GeoServer.
 * Each test uploads a real SLD generated by SldBuilder, verifies GeoServer accepts it,
 * then independently fetches the stored SLD via direct HTTP (curl-equivalent) and
 * compares that key elements round-trip correctly.
 */
@DisplayName("[LiveTest] SldBuilder → GeoServer")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SldBuilderLiveTest extends BaseIntegrationTest {

    private static final long   TS = System.currentTimeMillis();
    private static final String WS = "sldlive_" + TS;

    private StyleManager styles;
    private String       authHeader;

    @BeforeAll
    void setUp() {
        client.workspaces().create(CreateWorkspaceRequest.of(WS));
        styles     = client.styles();
        authHeader = "Basic " + Base64.getEncoder().encodeToString(
                "admin:geoserver".getBytes(StandardCharsets.UTF_8));
    }

    @AfterAll
    void cleanUp() {
        try { client.workspaces().delete(WS, true); } catch (Exception ignored) {}
    }

    // ── helper: fetch stored SLD via direct HTTP ───────────────────────────

    private String fetchSldDirect(String styleName) throws IOException {
        URL url = new URL("http://localhost:8100/geoserver/rest/workspaces/" + WS
                        + "/styles/" + styleName + ".sld");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestProperty("Authorization", authHeader);
        conn.setRequestProperty("Accept", "application/vnd.ogc.sld+xml");
        conn.setRequestMethod("GET");
        int status = conn.getResponseCode();
        assertEquals(200, status,
                "Direct SLD fetch failed for " + styleName + ": HTTP " + status);
        BufferedReader br = new BufferedReader(
                new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8));
        StringBuilder sb = new StringBuilder();
        String line;
        while ((line = br.readLine()) != null) { sb.append(line).append('\n'); }
        br.close();
        return sb.toString();
    }

    private void createWsStyle(String name, StyleContent sld) {
        styles.createByWorkspace(WS, sld, name);
        assertTrue(styles.existsByWorkspace(WS, name), "Style must exist after create: " + name);
    }

    // ── [1] PolygonSymbolizer (fill + stroke) ──────────────────────────────

    @Test @Order(1)
    void polygon_fillAndStroke() throws Exception {
        String name = "poly_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .styleName(name)
                .rule("blue-poly")
                    .fill("#336699").fillOpacity(0.8).stroke("#000000", 1)
                .end().build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("336699") || stored.contains("336699".toLowerCase()),
                "fill color must round-trip");
        assertTrue(stored.contains("PolygonSymbolizer"), "PolygonSymbolizer must be present");
    }

    // ── [2] LineSymbolizer (dash, linecap, linejoin) ───────────────────────

    @Test @Order(2)
    void line_dashCapJoin() throws Exception {
        String name = "line_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("dashed")
                    .stroke("#CC0000", 2)
                        .dashArray("4 2")
                        .lineCap(LineCap.ROUND)
                        .lineJoin(LineJoin.ROUND)
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("LineSymbolizer"), "LineSymbolizer must be present");
        assertTrue(stored.contains("CC0000") || stored.contains("cc0000"), "color round-trips");
    }

    // ── [3] PointSymbolizer (WKN mark + fill + stroke) ─────────────────────

    @Test @Order(3)
    void point_wknMarkWithStroke() throws Exception {
        String name = "point_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("circle")
                    .mark(WellKnownName.CIRCLE)
                        .fill("#FF0000").stroke("#000000", 1).size(10)
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("PointSymbolizer"), "PointSymbolizer must be present");
        assertTrue(stored.contains("circle"), "WellKnownName=circle must round-trip");
    }

    // ── [4] PointSymbolizer (ExternalGraphic) ──────────────────────────────

    @Test @Order(4)
    void point_externalGraphic() throws Exception {
        String name = "extg_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("icon")
                    .externalPoint("http://example.org/icon.png", "image/png")
                        .size(16)
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("ExternalGraphic"), "ExternalGraphic must be present");
        assertTrue(stored.contains("image/png"), "Format must round-trip");
    }

    // ── [5] TextSymbolizer (attribute label + halo + bold) ─────────────────

    @Test @Order(5)
    void text_labelWithHalo() throws Exception {
        String name = "text_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("label")
                    .label("NAME")
                        .color("#333333")
                        .font("Arial", 12)
                        .bold()
                        .halo("#FFFFFF", 2)
                        .vendorOption("labelObstacle", "true")
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("TextSymbolizer"), "TextSymbolizer must be present");
        assertTrue(stored.contains("Halo"), "Halo must be present");
    }

    // ── [6] TextSymbolizer (SldExpression label — OGC function) ────────────

    @Test @Order(6)
    void text_expressionLabel() throws Exception {
        String name = "texpr_" + TS;
        // GeoServer 2.28.2 kartoza image supports "Concatenate", not "strConcat"
        StyleContent sld = SldBuilder.create(name)
                .rule("concat-label")
                    .label(function("Concatenate",
                            property("NAME"),
                            literal(" ("),
                            property("TYPE"),
                            literal(")")))
                        .color("#000000")
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        // GeoServer normalizes the Concatenate function on storage — it accepts the SLD
        // (createWsStyle verifies 201+exists) and returns a TextSymbolizer.
        assertTrue(stored.contains("TextSymbolizer"), "TextSymbolizer must be present");
    }

    // ── [7] OGC Filter (equalTo) ────────────────────────────────────────────

    @Test @Order(7)
    void filter_equalTo() throws Exception {
        String name = "feq_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("highway").filter(equalTo("TYPE", "highway"))
                    .line("#FF0000", 3)
                .rule("other").elseFilter()
                    .line("#CCCCCC", 1)
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("Filter") || stored.contains("PropertyIsEqualTo"),
                "Filter must be present");
        assertTrue(stored.contains("ElseFilter") || stored.contains("elseFilter"),
                "ElseFilter must be present");
    }

    // ── [8] OGC Filter (scale denominators) ────────────────────────────────

    @Test @Order(8)
    void filter_scaleDenominators() throws Exception {
        String name = "fscale_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("zoomed-in").maxScale(50000)
                    .polygon("#336699")
                .rule("zoomed-out").minScale(50000)
                    .polygon("#99BBDD")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        assertTrue(stored.contains("MaxScaleDenominator") || stored.contains("maxScale"),
                "MaxScaleDenominator must be present");
        assertTrue(stored.contains("MinScaleDenominator") || stored.contains("minScale"),
                "MinScaleDenominator must be present");
    }

    // ── [9] OGC Filter (between, like, isNull) ─────────────────────────────

    @Test @Order(9)
    void filter_betweenLikeIsNull() throws Exception {
        String name = "fbetw_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("big").filter(between("POP", 100, 1000))
                    .polygon("#336699")
                .rule("named").filter(like("NAME", "A*"))
                    .polygon("#FF9900")
                .rule("noname").filter(isNull("NAME"))
                    .polygon("#CCCCCC")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("PropertyIsBetween") || stored.contains("Between"),
                "Between filter must be present");
    }

    // ── [10] OGC Filter (logical AND/OR/NOT) ───────────────────────────────

    @Test @Order(10)
    void filter_logicalAndOrNot() throws Exception {
        String name = "flogic_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("combined")
                    .filter(and(greaterThan("POP", 1000), like("NAME", "S*")))
                    .polygon("#336699")
                .rule("negated")
                    .filter(not(equalTo("TYPE", "lake")))
                    .polygon("#FF9900")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertFalse(stored.isEmpty(), "stored SLD must not be empty");
    }

    // ── [11] OGC Filter (spatial BBOX) ─────────────────────────────────────

    @Test @Order(11)
    void filter_spatialBbox() throws Exception {
        String name = "fbbox_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("in-bbox")
                    .filter(bbox("the_geom", -180, -90, 180, 90, "EPSG:4326"))
                    .polygon("#336699")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("BBOX") || stored.contains("Filter"),
                "BBOX filter must be present");
    }

    // ── [12] SldExpression arithmetic (proportional symbol) ────────────────

    @Test @Order(12)
    void expression_arithmeticSize() throws Exception {
        String name = "earith_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("proportional")
                    .mark(WellKnownName.CIRCLE)
                        .fill("#FF0000")
                        .size(mul(property("VALUE"), literal(0.01)))
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("PointSymbolizer"), "PointSymbolizer must be present");
    }

    // ── [13] Multiple FeatureTypeStyle (z-order) ───────────────────────────

    @Test @Order(13)
    void multipleFeatureTypeStyle_zOrder() throws Exception {
        String name = "multifts_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .ftsSemanticTypeIdentifier("generic:polygon")
                .rule("fill").polygon("#336699")
                .featureTypeStyle("labels")
                    .ftsSemanticTypeIdentifier("generic:text")
                    .rule("label").label("NAME").color("#000000").end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);

        long ftsCount = countOccurrences(stored, "FeatureTypeStyle");
        assertTrue(ftsCount >= 2, "Must have at least 2 FeatureTypeStyle blocks, got: " + ftsCount);
    }

    // ── [14] Multiple UserStyle ─────────────────────────────────────────────

    @Test @Order(14)
    void multipleUserStyle() throws Exception {
        String name = "multius_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .styleName("default-style").title("Default")
                .rule("default").polygon("#336699")
                .userStyle("highlight-style")
                    .rule("highlight").polygon("#FF0000")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        // GeoServer may collapse or keep multiple UserStyle — at minimum must accept the SLD
        assertFalse(stored.isEmpty(), "GeoServer must return stored SLD");
    }

    // ── [15] RasterSymbolizer (ColorMap) ───────────────────────────────────

    @Test @Order(15)
    void raster_colorMap() throws Exception {
        String name = "raster_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("dem-color")
                    .rasterBuilder()
                        .opacity(0.9)
                        .channelGray("1")
                        .colorMap(SldColorMapType.RAMP,
                                SldColorMapEntry.of("#0000FF", 0,   "Low",  1.0),
                                SldColorMapEntry.of("#00FF00", 500, "Mid",  1.0),
                                SldColorMapEntry.of("#FF0000", 1000,"High", 1.0))
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("RasterSymbolizer"), "RasterSymbolizer must be present");
        assertTrue(stored.contains("ColorMap") || stored.contains("colorMap"),
                "ColorMap must be present");
    }

    // ── [16] PolygonSymbolizer (GraphicFill pattern) ───────────────────────

    @Test @Order(16)
    void polygon_graphicFillPattern() throws Exception {
        String name = "pgfill_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("hatch")
                    .fill()
                        .fillPattern(WellKnownName.X, "#999999", 8)
                        .stroke("#000000", 1)
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("PolygonSymbolizer"), "PolygonSymbolizer must be present");
    }

    // ── [17] LinePlacement label ────────────────────────────────────────────

    @Test @Order(17)
    void text_linePlacement() throws Exception {
        String name = "tline_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("road-label")
                    .label("NAME")
                        .color("#000000")
                        .linePlacement(0)
                        .vendorOption("followLine", "true")
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("LinePlacement") || stored.contains("linePlacement"),
                "LinePlacement must be present");
    }

    // ── [18] Multiple font families ─────────────────────────────────────────

    @Test @Order(18)
    void text_multipleFontFamilies() throws Exception {
        String name = "tfont_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("fallback-font")
                    .label("NAME")
                        .fontFamilies("Arial", "Helvetica", "SansSerif")
                        .color("#000000")
                    .end()
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("TextSymbolizer"), "TextSymbolizer must be present");
    }

    // ── [19] FeatureId filter ───────────────────────────────────────────────

    @Test @Order(19)
    void filter_featureId() throws Exception {
        String name = "ffid_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("selected")
                    .filter(featureId("roads.1", "roads.2"))
                    .line("#FF0000", 3)
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertFalse(stored.isEmpty(), "stored SLD must not be empty");
    }

    // ── [20] NamedStyle reference → buildForNamedStyle ──────────────────────
    // GeoServer cannot store a NamedStyle-only SLD as a style resource (no symbolizers).
    // We verify the builder generates correct XML locally instead.
    @Test @Order(20)
    void namedStyleRef() {
        String refName = "nsref_real_" + TS;

        StyleContent namedRef = SldBuilder.create(refName)
                .namedStyle(refName)
                .buildForNamedStyle();

        String xml = namedRef.getSldBody();
        assertTrue(xml.contains("NamedStyle"), "NamedStyle element must be in generated SLD");
        assertTrue(xml.contains(refName), "NamedStyle Name must match");
        assertTrue(xml.contains("StyledLayerDescriptor"), "Root SLD element must be present");
    }

    // ── [21] LegendGraphic ──────────────────────────────────────────────────

    @Test @Order(21)
    void rule_legendGraphic() throws Exception {
        String name = "legend_" + TS;
        StyleContent sld = SldBuilder.create(name)
                .rule("r")
                    .legendGraphicMark(WellKnownName.SQUARE, "#336699", 16)
                    .polygon("#336699")
                .build();

        createWsStyle(name, sld);
        String stored = fetchSldDirect(name);
        assertTrue(stored.contains("LegendGraphic") || stored.contains("legendGraphic"),
                "LegendGraphic must be present");
    }

    // ── [22] SldBuilder vs raw SLD: same GeoServer response ────────────────

    @Test @Order(22)
    void sldBuilder_vs_rawSld_sameGeoServerBehavior() throws Exception {
        String builderName = "cmp_builder_" + TS;
        String rawName     = "cmp_raw_"     + TS;

        // SldBuilder version
        StyleContent builderSld = SldBuilder.create(builderName)
                .styleName(builderName)
                .rule("r").polygon("#336699").build();
        createWsStyle(builderName, builderSld);

        // Equivalent raw SLD
        String rawXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<StyledLayerDescriptor version=\"1.0.0\"\n"
                + "    xmlns=\"http://www.opengis.net/sld\"\n"
                + "    xmlns:ogc=\"http://www.opengis.net/ogc\"\n"
                + "    xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n"
                + "  <NamedLayer>\n"
                + "    <Name>" + rawName + "</Name>\n"
                + "    <UserStyle>\n"
                + "      <Name>" + rawName + "</Name>\n"
                + "      <FeatureTypeStyle>\n"
                + "        <Rule>\n"
                + "          <PolygonSymbolizer>\n"
                + "            <Fill>\n"
                + "              <CssParameter name=\"fill\">#336699</CssParameter>\n"
                + "            </Fill>\n"
                + "          </PolygonSymbolizer>\n"
                + "        </Rule>\n"
                + "      </FeatureTypeStyle>\n"
                + "    </UserStyle>\n"
                + "  </NamedLayer>\n"
                + "</StyledLayerDescriptor>";
        createWsStyle(rawName, StyleContent.of(rawXml));

        // Both must exist and return SLD
        String builderStored = fetchSldDirect(builderName);
        String rawStored     = fetchSldDirect(rawName);

        // Both contain PolygonSymbolizer
        assertTrue(builderStored.contains("PolygonSymbolizer"),
                "builder SLD: PolygonSymbolizer must be present");
        assertTrue(rawStored.contains("PolygonSymbolizer"),
                "raw SLD: PolygonSymbolizer must be present");

        // Both contain the fill color
        assertTrue(builderStored.contains("336699"),
                "builder SLD: fill color must round-trip");
        assertTrue(rawStored.contains("336699"),
                "raw SLD: fill color must round-trip");
    }

    // ── helper ──────────────────────────────────────────────────────────────

    private static long countOccurrences(String text, String needle) {
        long count = 0;
        int idx = 0;
        while ((idx = text.indexOf(needle, idx)) != -1) { count++; idx++; }
        return count;
    }
}
